
        document.addEventListener('DOMContentLoaded', async () => {

            const container = document.getElementById('termsContainer');

            const searchInput = document.getElementById('searchInput');

            let allTerms = [];



            try {

                // Fetch the JSON generated by our generate-dictionary.js script

                const response = await fetch('/data/dictionary-index.json');

                if (!response.ok) throw new Error('Data index nebyl nalezen');

                allTerms = await response.json();

                renderTerms(allTerms);

            } catch (err) {

                console.error(err);

                container.innerHTML = '<div class="no-results">Zatím nebyly přidány žádné pojmy. Hvězdy mlčí.</div>';

            }



            searchInput.addEventListener('input', (e) => {

                const query = e.target.value.toLowerCase();

                const filtered = allTerms.filter(t =>

                    t.title.toLowerCase().includes(query) ||

                    (t.short_description && t.short_description.toLowerCase().includes(query)) ||

                    (t.category && t.category.toLowerCase().includes(query))

                );

                renderTerms(filtered);

            });



            function renderTerms(terms) {

                container.innerHTML = '';

                if (terms.length === 0) {

                    container.innerHTML = '<div class="no-results">Nebyl nalezen žádný pojem odpovídající vašemu zadání.</div>';

                    return;

                }



                terms.forEach(term => {

                    const el = document.createElement('a');

                    el.href = `slovnik/${term.slug}.html`;

                    el.className = 'term-card';

                    el.innerHTML = `

                        <div class="term-category">${term.category || 'Obecné'}</div>

                        <div class="term-title">${term.title}</div>

                        <div class="term-desc">${term.short_description || ''}</div>

                    `;

                    container.appendChild(el);

                });

            }

        });
