-- ============================================
-- ANGEL MESSAGES TABLE
-- Spusťte tento skript v Supabase SQL Editoru
-- ============================================

-- 1. Vytvoření tabulky
CREATE TABLE IF NOT EXISTS public.angel_messages (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nickname VARCHAR(50) DEFAULT 'Anonym',
    message TEXT NOT NULL,
    category VARCHAR(20) DEFAULT 'jine',
    likes INTEGER DEFAULT 0,
    approved BOOLEAN DEFAULT true,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 2. Vytvoření indexů pro bleskové načítání feedu
CREATE INDEX IF NOT EXISTS idx_angel_messages_created_at ON public.angel_messages(created_at DESC);
CREATE INDEX IF NOT EXISTS idx_angel_messages_approved ON public.angel_messages(approved);

-- 3. Zabezpečení databáze proti přímému zápisu uživatelů mimo náš Node/API backend
ALTER TABLE public.angel_messages ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Public can view approved messages" ON public.angel_messages
    FOR SELECT USING (approved = true);

-- 4. Bezpečná SQL funkce pro započítávání srdíček (Likes) pomocí transakce
CREATE OR REPLACE FUNCTION public.increment_angel_likes(msg_id bigint)
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
BEGIN
  UPDATE public.angel_messages
  SET likes = COALESCE(likes, 0) + 1
  WHERE id = msg_id;
END;
$$;
