-- Create table for Mentor Chat History
create table if not exists mentor_messages (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users not null,
  role text not null check (role in ('user', 'mentor')),
  content text not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable Row Level Security (RLS)
alter table mentor_messages enable row level security;

-- Create policy to allow users to see only their own messages
create policy "Users can view their own mentor messages"
on mentor_messages for select
using ( auth.uid() = user_id );

-- Create policy to allow users to insert their own messages (or server can bypass RLS with service key)
create policy "Users can insert their own mentor messages"
on mentor_messages for insert
with check ( auth.uid() = user_id );

-- (Optional) Enable vector extension if not enabled
-- create extension if not exists vector;

-- (Optional) Add embedding column for future RAG
-- alter table mentor_messages add column embedding vector(768);
